version: 1

sources:
  - name: raw
    schema: gz_raw_data
    description: data from greenweez
    tables:
      - name: product
        identifier: raw_gz_product
        description: product list with purchase price
        columns:
          - name: products_id
            description: distinct id for a specific product
            tests:
              - unique
              - not_null
          - name: purchase_price
            description: cost of product acquisition
      - name: sales
        identifier: raw_gz_sales
        description: daily sales data
        loaded_at_field: "CAST(date_date AS TIMESTAMP)"
        freshness:
          warn_after: {count: 90, period: day}
        columns:
          - name: date_date
            description: date of purchase
          - name: orders_id
            description: distinct id for sales made
          - name: products_id
            description: distinct id for products sold
          - name: revenue
            description: turnover for a particular product
          - name: quantity
            description: quantity purchased for a specific product
        tests:
          - unique:
              column_name: "(orders_id || '-' || pdt_id)"
      - name: ship
        identifier: raw_gz_ship
        description: orders' shipping data
        columns:
          - name: orders_id
            description: distinct id for sales made
            tests:
              - unique
              - not_null
          - name: shipping_fee
            description: revenue made for shipment of product
          - name: log_cost
            description: cost of storing products
          - name: ship_cost
            description: cost of shipping products