version: 1
  
sources:
  - name: raw
    schema: gz_raw_data
    description: data from greenweez
    tables:
      - name: product
        identifier: raw_gz_product
        description: product list with purchase price
        columns:
          - name: products_id
            description: distinct id for a specific product
            tests:
              - unique
              - not_null
          - name: purchase_price
            description: cost of product acquisition
      - name: sales
        identifier: raw_gz_sales
        description: daily sales data
        loaded_at_field: "CAST(date_date AS TIMESTAMP)"
        freshness:
          warn_after: {count: 90, period: day}
        columns:
          - name: date_date
            description: date of purchase
          - name: orders_id
            description: distinct id for sales made
          - name: products_id
            description: distinct id for products sold
          - name: revenue
            description: turnover for a particular product
          - name: quantity
            description: quantity purchased for a specific product
        tests:
          - unique:
              column_name: "(orders_id || '-' || pdt_id)"
      - name: ship
        identifier: raw_gz_ship
        description: orders' shipping data
        columns:
          - name: orders_id
            description: distinct id for sales made
            tests:
              - unique
              - not_null
          - name: shipping_fee
            description: revenue made for shipment of product
          - name: log_cost
            description: cost of storing products
          - name: ship_cost
            description: cost of shipping products
      - name: adwords
        identifier: raw_gz_adwords
        description: campaign details from adwords
        columns:
          - name: date_date
            description: campaign date
          - name: paid_source
            description: campaign source
          - name: campaign_key
            description: campaign key
          - name: camPGN_name
            description: campaign name
          - name: ads_cost
            description: cost of the ad
          - name: impression
            description: number of impressions
          - name: click
            description: number of clicks
      - name: bing
        identifier: raw_gz_bing
        description: campaign details from bing
        columns:
          - name: date_date
            description: campaign date
          - name: paid_source
            description: campaign source
          - name: campaign_key
            description: campaign key
          - name: camPGN_name
            description: campaign name
          - name: ads_cost
            description: cost of the ad
          - name: impression
            description: number of impressions
          - name: click
            description: number of clicks
      - name: criteo
        identifier: raw_gz_criteo
        description: campaign details from criteo
        columns:
          - name: date_date
            description: campaign date
          - name: paid_source
            description: campaign source
          - name: campaign_key
            description: campaign key
          - name: camPGN_name
            description: campaign name
          - name: ads_cost
            description: cost of the ad
          - name: impression
            description: number of impressions
          - name: click
            description: number of clicks  
      - name: facebook
        identifier: raw_gz_facebook
        description: campaign details from facebook
        columns:
          - name: date_date
            description: campaign date
          - name: paid_source
            description: campaign source
          - name: campaign_key
            description: campaign key
          - name: camPGN_name
            description: campaign name
          - name: ads_cost
            description: cost of the ad
          - name: impression
            description: number of impressions
          - name: click
            description: number of clicks
models:
  - name: int_sales_margin
    description: joining of sales and products to compute for margin
    columns:
      - name: date_date
        description: date of sale
      - name: orders_id
        description: unique id for transaction
      - name: products_id
        description: unique id for product sold
      - name: revenue
        description: turnover for a particular product
      - name: quantity
        description: quantity purchased for a specific product
      - name: purchase_price
        description: cost of product acquisition
      - name: purchase_cost
        description: quantity times purchase price
      - name: margin
        description: revenue minus purchase cost
    tests:
      - unique:
          column_name: "(orders_id || '-' || products_id)"
  - name: int_orders_margin
    description: kpi computation by order id
    columns:
      - name: orders_id
        description: unique id for transaction
        tests:
          - unique
          - not_null
      - name: date_date
        description: date of sales
      - name: revenue
        description: turnover per order
      - name: quantity
        description: quantity per order
      - name: purchase_cost
        description: purchase cost per order
      - name: margin
        description: margin per order
  - name: int_orders_operational
    description: margin computation after shipping fees, log costs, and shipping costs
    columns:
      - name: orders_id
        description: unique id for transaction
        tests:
          - unique
          - not_null
      - name: date_date
        description: date of sales
      - name: revenue
        description: turnover per order
      - name: quantity
        description: quantity per order
      - name: purchase_cost
        description: purchase cost per order
      - name: margin
        description: margin per order
      - name: shipping_fee
        description: revenue made for shipment by order
      - name: log_cost
        description: cost of storing products by order
      - name: ship_cost
        description: cost of shipping products by order
      - name: operational_margin
        description: margin after shipping fee, log costs, and shipping costs
  - name: finance_days
    description: finance kpi cmputation by day
    columns:
      - name: date_date
        description: date of transaction
      - name: nb_transactions
        description: total number of transactions per day
  - name: int_campaigns
    description: combined campaign details from all ad sources
    columns:
      - name: date_date
        description: campaign date
      - name: paid_source
        description: campaign source
      - name: campaign_key
        description: campaign key
      - name: camPGN_name
        description: campaign name
      - name: ads_cost
        description: cost of the ad
      - name: impression
        description: number of impressions
      - name: click
        description: number of clicks
    tests:
      - unique:
          column_name: "(date_date || '-' || paid_source)"
  - name: int_campaigns_day
    description: aggregation by date of campaign data
    columns:
      - name: date_date
        description: campaign date
        tests:
          - unique
          - not_null
      - name: ads_cost
        description: cost of the ad
      - name: impression
        description: number of impressions
      - name: click
        description: number of clicks
          